services:
  app:
    build:
      context: .
      target: development
    volumes:
      - .:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run start-dev
    depends_on:
      - kafka
