services:
  app:
    build:
      context: .
      target: production
    environment:
      - NODE_ENV=production
    command: npm start
    restart: always
    depends_on:
      - kafka
  kafka:
    volumes:
      - kafka_data:/bitnami/kafka
    restart: always
volumes:
  kafka_data:
